import Head from 'next/head' 

export default function Home() {
  return (
    <>
      <Head>
        <title>Paradox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="flex">
          <div className="hidden lg:flex lg:flex-auto lg:justify-center lg:items-center w-20 lg:bg-cyan-500">
            <img src="/unindra-logo.png" className="w-96 h-96" alt="Gambar"/>
          </div>
          <div className="flex lg:flex-auto justify-center items-center h-screen w-full lg:w-80">
            <form className="flex justify-center items-center flex-col lg:w-full">
              <img src="/unindra-logo.png" className="w-16 lg:hidden" alt="Gambar"/>
              <h1 className="mt-5 mb-14 text-xl lg:text-3xl">Welcome</h1>
              <input className="mb-4 border-2 px-4 py-2 lg:w-96" type="text" placeholder="Username"/>
              <input className="mt-4 border-2 px-4 py-2 lg:w-96" type="password" placeholder="Password"/>
            </form>
          </div>
        </section>
      </main>
    </>
  )
}