import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Paradox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="flex">
          <div className="flex-1 hidden lg:block">
            <img src="/unindra-logo.png" className="" alt="Gambar"/>
          </div>
          <div className="flex justify-center items-center h-screen w-full">
            <form className="flex justify-center items-center flex-col">
              <img src="/unindra-logo.png" className="w-16" alt="Gambar"/>
              <h1 className="mt-5 mb-14 text-xl">Welcome</h1>
              <input className="w-100 mb-4 border-2 px-4 py-2" type="text" placeholder="Username"/>
              <input className="w-100 mt-4 border-2 px-4 py-2" type="password" placeholder="Password"/>
            </form>
          </div>
        </section>
      </main>
    </>
  )
}